In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

In [11]:
dataset=pd.read_excel("kredi_veriseti.xlsx")
dataset.head()

cinsiyet  yas  maas  kredi
0    Erkek   22  2200      0
1    Erkek   38  2300      0
2    Kadın   29  4600      0
3    Kadın   30  6000      0
4    Erkek   22  7900      0

In [12]:
one_hot= OneHotEncoder(handle_unknown='ignore')
one_hot_cinsiyet=one_hot.fit_transform(dataset['cinsiyet'].values.reshape(-1,1)).toarray()

In [14]:
one_hot.categories_

[array(['Erkek', 'Kadın'], dtype=object)]

In [15]:
one_hot_df=pd.DataFrame(one_hot_cinsiyet,columns=one_hot.categories_)
one_hot_df.head()

Erkek Kadın
0   1.0   0.0
1   1.0   0.0
2   0.0   1.0
3   0.0   1.0
4   1.0   0.0

In [16]:
one_hot_df2= dataset.join(one_hot_df)
one_hot_df2.head()

cinsiyet  yas  maas  kredi  (Erkek,)  (Kadın,)
0    Erkek   22  2200      0       1.0       0.0
1    Erkek   38  2300      0       1.0       0.0
2    Kadın   29  4600      0       0.0       1.0
3    Kadın   30  6000      0       0.0       1.0
4    Erkek   22  7900      0       1.0       0.0

In [17]:
one_hot_df2.drop('cinsiyet',axis=1,inplace=True)
one_hot_df2.head()

yas  maas  kredi  (Erkek,)  (Kadın,)
0   22  2200      0       1.0       0.0
1   38  2300      0       1.0       0.0
2   29  4600      0       0.0       1.0
3   30  6000      0       0.0       1.0
4   22  7900      0       1.0       0.0

In [18]:
X=one_hot_df2.drop('kredi',axis=1)
y=one_hot_df2['kredi']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
train_test_split?

In [21]:
 X_train, X_test, y_train, y_test = train_test_split(X,
                                                     y,
                                                     test_size=0.33,
                                                     random_state=42)

In [23]:
X_train.shape

(268, 4)

In [25]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [26]:
sc=StandardScaler()

In [27]:
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [28]:
X_train

array([[ 2.0052225 ,  0.72479792, -0.97785703,  0.97785703],
       [-1.22740379, -1.43119212,  1.02264438, -1.02264438],
       [ 0.33993017, -0.33843005,  1.02264438, -1.02264438],
       ...,
       [ 0.53584692,  1.84709411, -0.97785703,  0.97785703],
       [ 0.14401343,  0.19318394,  1.02264438, -1.02264438],
       [-0.54169518,  0.45899093, -0.97785703,  0.97785703]])

In [30]:
model=LogisticRegression(random_state=0)
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [31]:
y_pred= model.predict(X_test)

In [36]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0],
      dtype=int64)

In [37]:
y_test.values

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
      dtype=int64)

In [41]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [39]:
confusion_matrix(y_test,y_pred)

array([[78,  2],
       [19, 33]], dtype=int64)

In [40]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.80      0.97      0.88        80\n           1       0.94      0.63      0.76        52\n\n    accuracy                           0.84       132\n   macro avg       0.87      0.80      0.82       132\nweighted avg       0.86      0.84      0.83       132\n'

In [42]:
accuracy_score(y_test,y_pred)

0.8409090909090909